
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author madhvik
 */
public class Manage_Categories extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Categories
     */
    File ph;
    JFileChooser jfc;
    ArrayList<Category> al=new ArrayList<>();
    myTableModel tm;
    public Manage_Categories() {
        initComponents();
        setSize(800,400);
        load_category();
        tm=new myTableModel();
        mytable.setModel(tm);
    }
    
    void load_category(){
        al.clear();
        
        String ans=myClient.fetchcat();
        System.out.println(ans);
        StringTokenizer st=new StringTokenizer(ans,";;");
        while(st.hasMoreTokens()){
            String row=st.nextToken();
            StringTokenizer st1=new StringTokenizer(row,"$");
            String name=st1.nextToken();
            String photo=st1.nextToken();
            al.add(new Category(name,photo));
        }
        
    }
class myTableModel extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
           if(columnIndex==0)return al.get(rowIndex).name;
           else return al.get(rowIndex).photo;
        }

        @Override
        public String getColumnName(int column) {
            String names[]={"Name","Photo"};
            return names[column];
        }
        
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mytable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        catname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Browse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Categories");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 40);

        jLabel2.setText("Add Category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 110, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("View Category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(457, 60, 300, 16);

        mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mytable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 90, 300, 220);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 340, 72, 23);

        jLabel4.setText("Category name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 110, 16);

        catname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catnameActionPerformed(evt);
            }
        });
        getContentPane().add(catname);
        catname.setBounds(30, 140, 160, 30);

        jLabel5.setText("Photo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 180, 70, 20);
        getContentPane().add(photolb);
        photolb.setBounds(30, 220, 130, 120);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 320, 100, 23);

        Browse.setText("Browse");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });
        getContentPane().add(Browse);
        Browse.setBounds(180, 250, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catnameActionPerformed

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        // TODO add your handling code here:
        jfc=new JFileChooser();
        int ans=jfc.showOpenDialog(this);
        if(ans==JFileChooser.APPROVE_OPTION){
            ph=jfc.getSelectedFile();
            ImageIcon ic=new ImageIcon(ph.getPath());
            Image img=ic.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic1=new ImageIcon(img);
            photolb.setIcon(ic1);
            
        }
    }//GEN-LAST:event_BrowseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String category=catname.getText();
       
        String ans=myClient.addCategory(category,ph);
        if(ans.trim().equals("success")){
            JOptionPane.showMessageDialog(rootPane, "Category added");
            catname.setText("");
            photolb.setIcon(null);
            load_category();
            tm.fireTableDataChanged();
        
        }
        else JOptionPane.showMessageDialog(rootPane, ans);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ans=mytable.getSelectedRow();
        if(ans==-1){
            JOptionPane.showMessageDialog(rootPane, "Please select a row");
        }
        else{
            String ans1=myClient.deletecat(al.get(ans).name);
            if(ans1.trim().equals("success")){
                JOptionPane.showMessageDialog(rootPane, "Deleted successfully");
                load_category();
                tm.fireTableDataChanged();
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, ans1);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JTextField catname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mytable;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
